/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Clases.ConectarBase;
import javax.swing.JOptionPane;
import Clases.Cifrar;
import java.sql.SQLException;
import java.sql.PreparedStatement;

/**
 *
 * @author SIGLO XXI-PC30
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */
    boolean valida=false;
    ConectarBase conexion;
    PreparedStatement cmd;
    
    StringBuilder cadena2;
    
    
    public Registrar() {
        initComponents();
    
        this.setLocationRelativeTo(null);
        this.setResizable(true);
        deshabilitarComponentes();
        conexion= new ConectarBase();
    
    }
    
    public void deshabilitarComponentes(){
    
        btnSave.setEnabled(false);
        txtNombre.setEnabled(false);
        txtAM.setEnabled(false);
        txtAP.setEnabled(false);
        txtEmail.setEnabled(false);
        txtPasswordI.setEnabled(false);
        txtPasswordII.setEnabled(false);
        
    
    }
    
     public void habilitarComponentes(){
    
       // btnSave.setEnabled(true);
        txtNombre.setEnabled(true);
        txtAM.setEnabled(true);
        txtAP.setEnabled(true);
        txtEmail.setEnabled(true);
        txtPasswordI.setEnabled(true);
        txtPasswordII.setEnabled(true);
        
    }
     
       private void limpiarComponentes(){
       
        txtNombre.setText("");txtAP.setText("");
        txtAM.setText("");txtEmail.setText("");
        txtPasswordI.setText("");txtPasswordII.setText("");
       
    }
     private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        // TODO add your handling code here:
        //this.dispose();
        PantallaInicio Inicio=new PantallaInicio();
        Inicio.setVisible(true);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtAP = new javax.swing.JTextField();
        txtAM = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblRegresar1 = new javax.swing.JLabel();
        txtPasswordI = new javax.swing.JPasswordField();
        txtPasswordII = new javax.swing.JPasswordField();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(174, 214, 241));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nombre: ");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido Paterno:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido Materno:  ");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo Electronico: ");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña: ");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirmar Contraseña:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        lblRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/return.png"))); // NOI18N
        lblRegresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresar1MouseClicked(evt);
            }
        });

        txtPasswordI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordIActionPerformed(evt);
            }
        });
        txtPasswordI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordIKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordIKeyTyped(evt);
            }
        });

        txtPasswordII.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordIIKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordIIKeyTyped(evt);
            }
        });

        btnNew.setText("new");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton1.setText("Prueba");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtAP)
                            .addComponent(txtEmail)
                            .addComponent(txtAM, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPasswordI))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPasswordII)))
                .addGap(172, 172, 172))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblRegresar1)
                .addGap(180, 180, 180)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave)
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegresar1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNew)
                            .addComponent(btnSave)))
                    .addComponent(jButton1))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAM, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPasswordI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPasswordII, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresar1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        PantallaInicio p=new PantallaInicio();
        p.setVisible(true);
    }//GEN-LAST:event_lblRegresar1MouseClicked

    private void txtPasswordIIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordIIKeyTyped
        // TODO add your handling code here:
        
         StringBuilder cadena=new StringBuilder(txtPasswordII.getText());
        if(valida==false){        
         if(evt.isShiftDown()==true){
          if(evt.getKeyChar()<'A'||evt.getKeyChar()>'Z'){
           if (evt.getKeyChar()<'a'||evt.getKeyChar()>'z'){
            if(evt.getKeyChar()<'0'||evt.getKeyChar()>'9'){
             if (evt.getKeyChar()!='*'&&evt.getKeyChar()!='_'&&
                 evt.getKeyChar()!='#'&&evt.getKeyChar()!='&'){
            JOptionPane.showMessageDialog(rootPane,"Caracter incorrecto");
            cadena.deleteCharAt(cadena.length()-1);
            txtPasswordII.setText(cadena.toString());
            cadena=null;
            }
           }
          }          
        }
        }
         else{
            if(evt.getKeyChar()<'A'||evt.getKeyChar()>'Z'){
           if (evt.getKeyChar()<'a'||evt.getKeyChar()>'z'){
            if(evt.getKeyChar()<'0'||evt.getKeyChar()>'9'){
             if (evt.getKeyChar()!='*'&&evt.getKeyChar()!='_'&&
                 evt.getKeyChar()!='#'&&evt.getKeyChar()!='&'){
            JOptionPane.showMessageDialog(rootPane,"Caracter incorrecto");
            cadena.deleteCharAt(cadena.length()-1);
            txtPasswordII.setText(cadena.toString()); 
           }
          }
         }
        }
       }
      }
       
      valida=false;
        
    }//GEN-LAST:event_txtPasswordIIKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        if(txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Se requiere nombre");
            txtNombre.grabFocus();
        }else{
            if(txtAP.getText().isEmpty()){
        JOptionPane.showMessageDialog(rootPane,"Se requiere Apellido Paterno");
            txtAP.grabFocus();
        // Cifrar c=new Cifrar();
        //    JOptionPane.showMessageDialog(rootPane,c.getPassword(txtPass1.getText()));
        }else{
            if(txtAM.getText().isEmpty()){
        JOptionPane.showMessageDialog(rootPane,"Se requiere un Apellido Materno");
            txtAM.grabFocus();
        // Cifrar c=new Cifrar();
        //    JOptionPane.showMessageDialog(rootPane,c.getPassword(txtPass1.getText()));
            }else{
            if(txtEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Se requiere un E-mail");
            txtEmail.grabFocus();
        // Cifrar c=new Cifrar();
        //    JOptionPane.showMessageDialog(rootPane,c.getPassword(txtPass1.getText()));
        }
            else{
                
                if(txtPasswordI.getText().isEmpty()){
                
                   JOptionPane.showMessageDialog(rootPane,"Se requiere password");
                   txtPasswordI.grabFocus();
                    
                    }
                else{
                
                    try{
                    //numero de signos de interrogacion dependiendo al numero de datos a ingresar y guardadr en el orden de la base de datos
                        String insertar="INSERT INTO usuario(nombre,aPaterno,aMaterno,correo,contrasena) VALUES(?,?,?,?,?)";
                        cmd=(PreparedStatement)conexion.conectar.prepareStatement(insertar);
                        //empieza a asignar los valores a las variables dependiendo al numero que se le asigna
                        cmd.setString(1,txtNombre.getText());
                        //JOptionPane.showMessageDialog(rootPane,":)");
                        cmd.setString(2, txtAP.getText());
                        //JOptionPane.showMessageDialog(rootPane,"Gua");
                        cmd.setString(3, txtAM.getText());
                        //JOptionPane.showMessageDialog(rootPane,"Guar)");
                        cmd.setString(4,txtEmail.getText());
                        //JOptionPane.showMessageDialog(rootPane,"(:)");
                        Cifrar c=new Cifrar();
                        
                        cmd.setString(5,c.getPassword(txtPasswordI.getText().toUpperCase()));
                        //JOptionPane.showMessageDialog(rootPane,"Guardado  :)");
                        cmd.executeUpdate();
                         JOptionPane.showMessageDialog(rootPane,"Guardado con exito :)");
                         limpiarComponentes();
                         deshabilitarComponentes();
                       //  JOptionPane.showMessageDialog(rootPane,"Gun exito :)");
                         btnNew.setEnabled(true);
                        
                                
                    }catch(SQLException e){
                    
                        JOptionPane.showMessageDialog(rootPane,"Error al guardar"+e);
                    
                    }   
                    
                }
                }
            }
        }
        }
        Cifrar c=new Cifrar();
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombre=JOptionPane.showInputDialog("Escribe tu nombre:");
       // String edad=JOptionPane.showInputDialog(rootPane, btnSave, DISPOSE_ON_CLOSE)
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPasswordIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordIKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==10){
        valida=true;
        txtPasswordII.grabFocus();        
      }
       if(evt.getKeyCode()==8){
           valida=true;
      } 
        
    }//GEN-LAST:event_txtPasswordIKeyPressed

    private void txtPasswordIIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordIIKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==10){
        valida=true;
        confirmarPasswords();
      }
       if(evt.getKeyCode()==8){
           valida=true;
      } 
        
    }//GEN-LAST:event_txtPasswordIIKeyPressed

    private void txtPasswordIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordIKeyTyped
        // TODO add your handling code here:
        
        StringBuilder cadena=new StringBuilder(txtPasswordI.getText());
        if(valida==false){        
         if(evt.isShiftDown()==true){
          if(evt.getKeyChar()<'A'||evt.getKeyChar()>'Z'){
           if (evt.getKeyChar()<'a'||evt.getKeyChar()>'z'){
            if(evt.getKeyChar()<'0'||evt.getKeyChar()>'9'){
             if (evt.getKeyChar()!='*'&&evt.getKeyChar()!='_'&&
                 evt.getKeyChar()!='#'&&evt.getKeyChar()!='&'){
            JOptionPane.showMessageDialog(rootPane,"Caracter incorrecto");
            cadena.deleteCharAt(cadena.length()-1);
            txtPasswordI.setText(cadena.toString());
            cadena=null;
            }
           }
          }          
        }
        }
         else{
            if(evt.getKeyChar()<'A'||evt.getKeyChar()>'Z'){
           if (evt.getKeyChar()<'a'||evt.getKeyChar()>'z'){
            if(evt.getKeyChar()<'0'||evt.getKeyChar()>'9'){
             if (evt.getKeyChar()!='*'&&evt.getKeyChar()!='_'&&
                 evt.getKeyChar()!='#'&&evt.getKeyChar()!='&'){
            JOptionPane.showMessageDialog(rootPane,"Caracter incorrecto");
            cadena.deleteCharAt(cadena.length()-1);
            txtPasswordI.setText(cadena.toString()); 
           }
          }
         }
        }
       }
      }
       
      valida=false;
        
    }//GEN-LAST:event_txtPasswordIKeyTyped

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        habilitarComponentes();
        btnNew.setEnabled(false);
        btnSave.setEnabled(true);
        txtNombre.grabFocus();
    }//GEN-LAST:event_btnNewActionPerformed

    private void txtPasswordIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordIActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        
        //para poner enter en las cosas
        
    }//GEN-LAST:event_txtNombreKeyReleased

    private void confirmarPasswords(){
      if(txtPasswordI.getText().matches(txtPasswordII.getText())){
          btnSave.grabFocus();
      }
      else{
          JOptionPane.showMessageDialog(rootPane,"No coincide el password, verifique");
          txtPasswordII.setText("");
          txtPasswordI.grabFocus();
      }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRegresar1;
    private javax.swing.JTextField txtAM;
    private javax.swing.JTextField txtAP;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPasswordI;
    private javax.swing.JPasswordField txtPasswordII;
    // End of variables declaration//GEN-END:variables

    private static class RegistroUsuario {

        public RegistroUsuario() {
        }
    }
}
